[package]
name = "axe-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "axe"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
logos = "0.14"
thiserror = "1.0"
